### ISSUE TITLE
Any channce of an Apple Silicon build?

### ISSUE THREAD

**Issue by iamnhx** [Alkl58/RcloneBrowser#7]
As above :)

**Comment by Alkl58** [comment]
For that someone with experience compiling on Apple Silicon would be necessary. 

As I don't have any Apple Devices, someone else would have to do it.

**Comment by jimtje** [comment]
Hey, just wanted to drop a note that it compiles on Sonoma without issue once you comment out lines 1622-1625 and 1979-1982 in src/remote_widget.cpp. However, I haven't been able to figure out how to link the dependencies of QT5 frameworks to the dylibs copied into the app bundle (on Qt5.15.1), but I think that's more of a problem with my installation of Qt@5 instead of the actual code. I compiled the bundle without the static libraries included on an M2 Max, latest Sonoma, and with cmake and qt@5 both from homebrew. The instructions are basically what the readme says except change the paths to your particular install location if needed.

I can't test every storage backend but SFTP, Dropbox, B2, and pcloud at least works without issue and I have no reason to believe that it would be too different for the other supported backends.

**Comment by iamnhx** [comment]
[Rclone Browser.zip](https://github.com/Alkl58/RcloneBrowser/files/12890559/Rclone.Browser.zip)
Try this. (arm64)
